/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basicjavaedittor;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.StringReader;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.*;

import javax.swing.event.UndoableEditEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import javax.swing.undo.UndoManager;

/**
 *
 * @author Juan-pinto
 */
public class BasicJavaEdittorForm extends javax.swing.JFrame implements ActionListener {

  UndoManager undoManager = new UndoManager();
  private JFileChooser chooser = new JFileChooser();
  File curFile;

  /**
   * Creates new form BasicJavaEdittorForm
   */
  public BasicJavaEdittorForm() {
    initComponents();

    btnSave.addActionListener(this);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnSave = new javax.swing.JButton();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuBar2 = new javax.swing.JMenuBar();
    jMenu3 = new javax.swing.JMenu();
    jMenu4 = new javax.swing.JMenu();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextPane1 = new javax.swing.JTextPane();
    btnSave6 = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    Save = new javax.swing.JMenuItem();
    print = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    Undo = new javax.swing.JMenuItem();
    Redo = new javax.swing.JMenuItem();
    jMenu5 = new javax.swing.JMenu();

    btnSave.setText("Save");

    jMenuItem2.setText("jMenuItem2");

    jMenuItem3.setText("jMenuItem3");

    jMenu3.setText("File");
    jMenuBar2.add(jMenu3);

    jMenu4.setText("Edit");
    jMenuBar2.add(jMenu4);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jScrollPane1.setViewportView(jTextPane1);

    btnSave6.setText("Save");
    btnSave6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSave6ActionPerformed(evt);
      }
    });

    jMenu1.setText("File");

    Save.setText("Save");
    Save.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveFileAction(evt);
      }
    });
    jMenu1.add(Save);

    print.setText("Print");
    jMenu1.add(print);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");

    Undo.setText("Undo");
    Undo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        UndoActionPerformed(evt);
      }
    });
    jMenu2.add(Undo);

    Redo.setText("Redo");
    Redo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        RedoActionPerformed(evt);
      }
    });
    jMenu2.add(Redo);

    jMenuBar1.add(jMenu2);

    jMenu5.setText("View");
    jMenuBar1.add(jMenu5);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(318, Short.MAX_VALUE)
            .addComponent(btnSave6))
          .addComponent(jScrollPane1))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSave6)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  public void undoableEditHappened(UndoableEditEvent e) {
    undoManager.addEdit(e.getEdit());
  }
  private void btnSave6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave6ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnSave6ActionPerformed

  private void saveFileAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileAction
    saveFile(null);
  }//GEN-LAST:event_saveFileAction

  private void RedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedoActionPerformed

  }//GEN-LAST:event_RedoActionPerformed

  private void UndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoActionPerformed
    // TODO add your handling code here:
    undo();

  }//GEN-LAST:event_UndoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BasicJavaEdittorForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem Redo;
  private javax.swing.JMenuItem Save;
  private javax.swing.JMenuItem Undo;
  private javax.swing.JButton btnSave;
  private javax.swing.JButton btnSave6;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenu jMenu4;
  private javax.swing.JMenu jMenu5;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuBar jMenuBar2;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextPane jTextPane1;
  private javax.swing.JMenuItem print;
  // End of variables declaration//GEN-END:variables

  public void saveFile(File f) {
    try {
      if (f == null || curFile == null) {
        //show chooser
        int retValue = chooser.showSaveDialog(this);
        if (retValue == JFileChooser.APPROVE_OPTION) {
          f = chooser.getSelectedFile();
        } else {
          return;
        }
      }
      BufferedReader reader = new BufferedReader(new StringReader(jTextPane1.getText()));
      BufferedWriter writer = new BufferedWriter(new FileWriter(f));
      String str;
      while ((str = reader.readLine()) != null) {
        writer.write(str + System.getProperty("line.separator"));
      }
      writer.flush();
      reader.close();
      writer.close();
      curFile = f;
      // dirty = false;
      setTitle("JWebEdit - " + f.getAbsolutePath());
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Error Saving File\n" + e.getLocalizedMessage());
    }
  }

  @Override
  public void actionPerformed(ActionEvent e) {
    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  }

  private void undo() {
    // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    if (undoManager.canUndo()) {
      try {
        undoManager.undo();
      } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An error occurred.  Can't Undo.\n" + e.getLocalizedMessage());
      }
    }
  }
}
